services:
  postgresql:
    container_name: postgresql
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Required
      - POSTGRES_USER=${POSTGRES_USER} # Optional
      # - POSTGRES_DB=${POSTGRES_DB} # Optional
    volumes:
      - ./vol/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.2
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL} # Required
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD} # Required
    volumes:
      - ./vol/pgadmin:/var/lib/pgadmin
    depends_on:
      postgresql:
        condition: service_healthy
